apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toby-site.yaml
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    path: k8s-deployments/toby-site
    repoURL: https://github.com/IanRobertsWork/websites.git
    targetRevision: HEAD