apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tobysite-hobby-app
  namespace: default
spec:
  dnsNames:
    - www.tobz0r.co.uk
  secretName: tobysite-hobby-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer