---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
        name: tobysite-hobby-dev
    spec:
        selector:
            matchLabels:
                app: tobysite-hobby-dev
        replicas: 1
        template:
            metadata:
                labels:
                    app: tobysite-hobby-dev
            spec:
                containers: 
                - name: tobysite-hobby-dev
                  image: tobz0r/websites:3
                  imagePullPolicy: Always


---
    apiVersion: v1
    kind: Service
    metadata:
        name: tobysite-hobby-dev-svc
    spec:
        selector:
            app: tobysite-hobby-dev
        ports:
            -
                name: http
                port: 8080
                targetPort: 80
                protocol: TCP

---
    apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    metadata:
        name: tobysite-hobby-dev-ingress
    spec:
        rules:
        - host: dev.tobz0r.co.uk
          http:
            paths:
            - path: /
              backend:
                serviceName: tobysite-hobby-dev-svc
                servicePort: 8080