apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: athena-app
  namespace: default
spec:
  dnsNames:
    - athena.elrosvirtual.co.uk
  secretName: athena-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer