---
    apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    metadata:
        name: glyons-svc
    spec:
        rules:
        - host: athena.elrosvirtual.co.uk
          http:
            paths:
            - path: /
              backend:
                serviceName: athena-moodle
                servicePort: 80