---
    apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    metadata:
        name: glyons-ingress
        # annotations:
        #   cert-manager.io/cluster-issuer: "letsencrypt-staging"
    spec:
      tls:
      - hosts:
        - athena.elrosvirtual.co.uk
        secretName: athena-app-tls
      rules:
        - host: athena.elrosvirtual.co.uk
          http:
            paths:
            - path: /
              backend:
                serviceName: athena-moodle
                servicePort: 80


