apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-app
  namespace: argocd
spec:
  dnsNames:
    - argocd.elrosvirtual.co.uk
  secretName: argo-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer