apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-app
  namespace: jenkins
spec:
  dnsNames:
    - jenkins.elrosvirtual.co.uk
  secretName: jenkins-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer