apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shayne-app
  namespace: default
spec:
  dnsNames:
    - shayne.elrosvirtual.co.uk
  secretName: shayne-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer