apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ian-site.yaml
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    path: ian-cv-site
    repoURL: https://github.com/Elros-Virtual/ir-portfolio.git
    targetRevision: HEAD