apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zerastuscore-app
  namespace: default
spec:
  dnsNames:
    - zerastuscore.elrosvirtual.co.uk
  secretName: zerastuscore-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer