apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: barrowfalls-app
  namespace: default
spec:
  dnsNames:
    - barrowfalls.elrosvirtual.co.uk
  secretName: barrowfalls-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer