apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elros-app
  namespace: default
spec:
  dnsNames:
    - www.elrosvirtual.co.uk
  secretName: elros-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer