apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ian-cv-app
  namespace: default
spec:
  dnsNames:
    - www.ianaroberts.co.uk
  secretName: ian-cv-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer