apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: castle-of-paint-app
  namespace: default
spec:
  dnsNames:
    - castle-of-paint.elrosvirtual.co.uk
  secretName: castle-of-paint-app-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer